---
target: ath79/nand
brand_nice: GL.iNet
model_nice: GL-XE300

switch_ports: 5
switch_int_port: 0
switch_ignore_ports: [1,2,3]

# wan port is separate device: eth1
int_port: eth0

wireless_devices:
  - name: 11g_standard
    band: 2g
    htmode_prefix: HT
    path: platform/ahb/18100000.wmac
    ifname_hint: wlan2

model__packages__to_merge:
  - kmod-usb-serial-option
  - picocom
